apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
      environment: staging
  template:
    metadata:
      labels:
        app: gateway
        environment: staging
    spec:
      containers:
      - name: gateway-container
        image: sarrlick/gateway:staging
        ports:
        - containerPort: 8000
        
