# users-chart/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "users-chart.fullname" . }}
  labels:
    {{- include "users-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }} # add this line for static node port on our environment
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "users-chart.selectorLabels" . | nindent 4 }}