apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
      environment: qa
  template:
    metadata:
      labels:
        app: orders
        environment: qa
    spec:
      containers:
      - name: orders-container
        image: sarrlick/orders:qa
        ports:
        - containerPort: 8000
        
