apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
      environment: dev
  template:
    metadata:
      labels:
        app: gateway
        environment: dev
    spec:
      containers:
      - name: gateway-container
        image: sarrlick/gateway:dev
        ports:
        - containerPort: 8000
        
