apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
      environment: dev
  template:
    metadata:
      labels:
        app: orders
        environment: dev
    spec:
      containers:
      - name: orders-container
        image: sarrlick/orders:dev
        ports:
        - containerPort: 8000
        
