apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
      environment: dev
  template:
    metadata:
      labels:
        app: users
        environment: dev
    spec:
      containers:
      - name: users-container
        image: sarrlick/users:dev
        ports:
        - containerPort: 8000
        
